export enum AiProvider {
  AmazonBedrock = 'amazon-bedrock',
  Anthropic = 'anthropic', 
  AzureOpenAi = 'azure-openai',
  Cartesia = 'cartesia',
  Cerebras = 'cerebras',
  Cohere = 'cohere',
  Deepseek = 'deepseek',
  ElevenLabs = 'elevenlabs',
  GoogleAiStudio = 'google-ai-studio',
  GoogleVertexAi = 'google-vertex-ai',
  Grok = 'grok',
  Groq = 'groq',
  HuggingFace = 'huggingface',
  MistralAi = 'mistral-ai',
  OpenAi = 'openai',
  OpenRouter = 'openrouter',
  Perplexity = 'perplexity',
  Replicate = 'replicate',
  WorkersAi = 'workers-ai'
}
